import Head from "next/head";
import React, { useState, useEffect } from "react";
import { getXataClient } from "../util/xata";
import Header from "../components/Header";
import IncomeForm from "../components/IncomeForm";
import IncomeList from "../components/IncomeList";

export default function Home({ incomes }: any) {
  console.log(incomes);
  const [income, setIncome] = useState([] as any[]);
  const [totalIncome, setTotalIncome] = useState(0);

  useEffect(() => {
    setIncome(incomes);
  }, [incomes]);

  useEffect(() => {
    console.log(income);
    let temp = 0;
    for (let i = 0; i < income.length; i++) {
      temp += parseInt(income[i].price);
    }

    setTotalIncome(temp);
  }, [income]);

  return (
    <div className="">
      <Head>
        <title>Income Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header totalIncome={totalIncome} />
        <IncomeForm income={income} setIncome={setIncome} />
        <IncomeList income={income} setIncome={setIncome} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const xata = await getXataClient();
  const incomes = await xata.db.incomes.getAll();
  console.log(incomes);
  return {
    props: {
      incomes: incomes.map(({ replace, ...income }) => ({
        ...income,
        date: income.date?.toISOString(),
      })),
    },
  };
}
